services:
  web:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - APP_PORT=${APP_PORT}
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  db_data: